In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [7]:
median_salary_year =df['salary_year_avg'].median()

In [10]:
median_salary_hour = df['salary_hour_avg'].median()

In [11]:
df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [12]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [19]:
salary_rate_before_fill = df['salary_rate'].head(10)
df_filled= df.fillna({'salary_rate': 'Unknown'})
salary_rate_after = df_filled['salary_rate'].head(10)
salary_rate_before_fill, salary_rate_after

(0    None
 1    None
 2    None
 3    None
 4    None
 5    None
 6    None
 7    None
 8    None
 9    None
 Name: salary_rate, dtype: object,
 0    Unknown
 1    Unknown
 2    Unknown
 3    Unknown
 4    Unknown
 5    Unknown
 6    Unknown
 7    Unknown
 8    Unknown
 9    Unknown
 Name: salary_rate, dtype: object)

In [14]:
df_unique = df_filled

df_unique.drop_duplicates()

df_unique = df_unique.drop_duplicates()

print('Length of original df:        ', len(df_filled))
print('Length of drop duplicates df: ', len(df_unique))
print('Rows Dropped:                 ', len(df_filled) - len(df_unique))

Length of original df:         785741
Length of drop duplicates df:  785640
Rows Dropped:                  101

In [15]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Length of original df:        ', len(df_filled))
print('Length of drop duplicates df: ', len(df_unique))
print('Rows Dropped:                 ', len(df_filled) - len(df_unique))

Length of original df:         785741
Length of drop duplicates df:  508042
Rows Dropped:                  277699

In [16]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df_with_salary_year_avg = df.dropna(subset=['salary_year_avg'])

print('Length of original df:        ', len(df))
print('Length of drop duplicates df: ', len(df_with_salary_year_avg))
print('Rows Dropped:                 ', len(df) - len(df_with_salary_year_avg))

Length of original df:         785741
Length of drop duplicates df:  22003
Rows Dropped:                  763738

In [ ]:
df_cleaned = df.drop_duplicates(subset=['job_location'])

print('Length of original df:        ', len(df))
print('Length of drop duplicates df: ', len(df_cleaned))
print('Rows Dropped:                 ', len(df) - len(df_cleaned))

Length of original df:         785741
Length of drop duplicates df:  17218
Rows Dropped:                  768523