In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
df.index.name = 'job_index'

In [6]:
df.head()

                job_title_short  ...                                    job_type_skills
job_index                        ...
0          Senior Data Engineer  ...                                               None
1                  Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2                 Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3                 Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4                 Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [7]:
df.index.dtype

dtype('int64')

In [11]:

df.reset_index(drop=True, inplace=True)
df.head()

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                               None
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 16 columns]

In [20]:
job_median_salary =df.pivot_table(index='job_title_short', values='salary_year_avg', aggfunc='median')
job_median_salary.reset_index(inplace=True)
job_median_salary.set_index('salary_year_avg', inplace=True)
job_median_salary.head()

                  job_title_short
salary_year_avg
85000.0          Business Analyst
90000.0            Cloud Engineer
90000.0              Data Analyst
125000.0            Data Engineer
127500.0           Data Scientist

                          job_title_short  ...                                    job_type_skills
job_posted_date                            ...
2023-06-16 13:44:15  Senior Data Engineer  ...                                               None
2023-01-14 13:18:07          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2023-10-10 13:14:55         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
2023-07-04 13:01:41         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
2023-08-07 14:29:36         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 16 columns]

In [17]:
pivot_table =df.pivot_table(index='company_name', values='salary_year_avg', aggfunc='median')
pivot_table.sort_index(inplace=True, ascending=False)
pivot_table.head()

                                    salary_year_avg
company_name
​Illinois State Board of Education          62536.0
Технологическая компания                   280000.0
ЛАНИТ                                      400000.0
ztp                                         95000.0
zooplus SE                                 161750.0