In [3]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [7]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
458130,Data Analyst,Data Analyst,Singapore,via BeBee Singapore,Full-time,False,Singapore,2023-12-08 14:32:35,True,False,Singapore,None,NaN,NaN,Good Job Creations Pte Ltd,"['java', 'python', 'sql', 'r']","{'programming': ['java', 'python', 'sql', 'r']}"
541432,Data Engineer,Data Center Engineer,Switzerland,via BeBee Schweiz,Full-time,False,Switzerland,2023-02-22 19:49:04,True,False,Switzerland,None,NaN,NaN,Reboot Monkeys B.V.,"['go', 'linux']","{'os': ['linux'], 'programming': ['go']}"
450560,Data Scientist,Sr Data Scientist,"Fremont, CA",via Simplify Jobs,Full-time,False,"California, United States",2023-01-03 23:32:37,False,True,United States,None,NaN,NaN,Weee!,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
26658,Data Engineer,Capitec Bank Vacancies for 2022 – Data Engineer I,"Cape Town, South Africa",via VacanciesHut,Full-time,False,South Africa,2023-01-01 14:08:56,False,False,South Africa,None,NaN,NaN,Capitec Bank,"['aws', 'redshift', 'word', 'excel', 'outlook']","{'analyst_tools': ['word', 'excel', 'outlook']..."
564997,Senior Data Analyst,Senior Data Analyst,Afghanistan,via Trabajo.org,Full-time,False,Afghanistan,2023-07-06 05:14:53,True,False,Afghanistan,None,NaN,NaN,Amway,None,None
725656,Data Scientist,Data Scientist,"Las Condes, Chile",via BeBee Chile,Full-time,False,Chile,2023-02-03 21:52:18,False,False,Chile,None,NaN,NaN,Equifax,"['python', 'sql', 'bigquery']","{'cloud': ['bigquery'], 'programming': ['pytho..."
476552,Data Analyst,Data Analyst,"Austin, TX",via ZipRecruiter,Full-time,False,"Texas, United States",2023-04-11 14:01:19,True,False,United States,None,NaN,NaN,Atolla Tech,"['matlab', 'python']","{'programming': ['matlab', 'python']}"
533466,Data Scientist,Marketing Data Scientist,"Cheltenham, UK",via BeBee,Full-time,False,United Kingdom,2023-12-25 19:23:41,False,False,United Kingdom,None,NaN,NaN,Ripjar,"['python', 'pytorch', 'scikit-learn', 'numpy',...","{'libraries': ['pytorch', 'scikit-learn', 'num..."
741924,Data Engineer,Data Engineer,Canada,via Trabajo.org,Full-time,False,Canada,2023-03-14 20:27:54,True,False,Canada,None,NaN,NaN,Carol Stream,None,None
31256,Senior Data Analyst,Senior Data Analyst,"Edinburgh, UK",via Totaljobs,Full-time,False,United Kingdom,2023-08-31 13:44:10,True,False,United Kingdom,None,NaN,NaN,Hamilton Forth,"['sql', 'python', 'tableau', 'qlik', 'flow']","{'analyst_tools': ['tableau', 'qlik'], 'other'..."

In [9]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df_copy = df.copy()
df_cleaned = df_copy.dropna(subset=['salary_year_avg'])
df_cleaned.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."

In [11]:
df_sample = df.sample(frac=0.1)
df_sample.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
240170,Data Analyst,"Manager, Data (Ads Data Team)",Poland,via Smart Recruiters Jobs,Full-time,False,Poland,2023-12-07 07:35:18,True,False,Poland,None,NaN,NaN,Allegro,"['sql', 'windows']","{'os': ['windows'], 'programming': ['sql']}"
683118,Data Analyst,Data Analyst (m/w/d) | Frankfurt,"Frankfurt, Germany",via XING,Full-time,False,Germany,2023-11-03 10:12:40,True,False,Germany,None,NaN,NaN,ADVERGY GmbH,None,None
11306,Data Scientist,"Consultant, Data Science & Analytics","Pune, Maharashtra, India",via Jooble,Full-time,False,India,2023-08-24 13:29:44,False,False,India,None,NaN,NaN,TransUnion,"['r', 'sas', 'sas', 'spark']","{'analyst_tools': ['sas'], 'libraries': ['spar..."
388229,Data Scientist,"Research Student, Ph.D. in Data Science","Skoghall, Sweden",via LinkedIn,Full-time,False,Sweden,2023-04-05 18:12:12,False,False,Sweden,None,NaN,NaN,Stora Enso,None,None
371675,Senior Data Engineer,Senior Lead Data Engineer,"Philadelphia, PA",via KHON2 Jobs,Full-time,False,"Florida, United States",2023-06-12 18:29:01,False,True,United States,year,246500.0,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."

In [12]:
median_salary_year = df['salary_year_avg'].median()
median_salary_year

115000.0

In [15]:
df_copy = df.copy()
df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_salary_year)
df_copy.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."